server:
  port: 9005
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.203.220:3306/mymall_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:
    host: 47.93.203.220
  rabbitmq:
    host: 47.93.203.220
    username: admin
    password: admin
    virtual-host: my_vhost
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
