server:
  port: 9016
spring:
  jackson:
    time-zone: GMT+8
  application:
    name: sparrow-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.203.220:3306/mymall_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: password
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:
    host: 47.93.203.220
#  rabbitmq:
#    host: 47.93.203.220
#    publisher-confirms: true  #开启confirm数据保护机制
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
