spring:
  application:
    name: sparrow-web-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
            - id: sparrow-seckill
              uri: lb://sparrow-seckill
              predicates:
                - Path=/seckill/**
              filters:
                - StripPrefix=1
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipKeyResolver}" #用户唯一标识
#                    redis-rate-limiter.replenishRate: 1000 #每秒钟允许多少个请求
#                    redis-rate-limiter.burstCapacity: 100 #允许并发有多少个请求
#        # 这里边包含了关于商品等一切操作
#        # 包括 下单 查询订单状态 结账等
#          - id: sparrow-seckillgoods
#            uri: lb://sparrow-order
#            predicates:
#              - Path=/api/goods/**
#            filters:
#              - StripPrefix=2
#              - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory RequestRateLimiterGatewayFilterFactory
#                args:
#                  key-resolver: "#{@ipKeyResolver}" #用户唯一标识
#                  redis-rate-limiter.replenishRate: 10 #每秒钟允许多少个请求
#                  redis-rate-limiter.burstCapacity: 50 #允许并发有多少个请求
#          - id: sparrow-seckillorder
#              uri: lb://sparrow-order
#              predicates:
#                - Path=/api/order/**
#              filters:
#                - StripPrefix=2
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipKeyResolver}" #用户唯一标识
#                    redis-rate-limiter.replenishRate: 10 #每秒钟允许多少个请求
#                    redis-rate-limiter.burstCapacity: 50 #允许并发有多少个请求
  redis:
    host: 47.93.203.220
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
#      defaultZone: http://47.93.203.220:6868/eureka
  instance:
    prefer-ip-address: true